/*
 * Copyright © 2020-2021, Simplexion, Hungary and contributors. Use of this source code is governed by the Apache 2.0 license.
 */
package zakadabar.stack.backend.data.exposed

import org.jetbrains.exposed.dao.id.LongIdTable
import org.jetbrains.exposed.sql.ResultRow
import org.jetbrains.exposed.sql.statements.UpdateBuilder
import zakadabar.stack.data.entity.EntityBo

/**
 * Exposed table that supports BO mapping. The mapping is usually generated by
 * Bender.
 */
abstract class ExposedPaTable<T : EntityBo<T>>(tableName: String) : LongIdTable(tableName) {
    abstract fun toBo(row: ResultRow): T
    abstract fun fromBo(statement: UpdateBuilder<*>, bo: T)
}