/*
 * Copyright © 2020-2021, Simplexion, Hungary and contributors. Use of this source code is governed by the Apache 2.0 license.
 */
package zakadabar.rui.runtime

/**
 * Base class for fragments generated by the compiler plugin.
 */
@RuiPublicApi
abstract class RuiGeneratedFragment<BT>(
    override val ruiAdapter : RuiAdapter<BT>,
    override val ruiExternalPatch : (it : RuiFragment<BT>) -> Unit
) : RuiFragment<BT> {

    abstract val fragment : RuiFragment<BT>

    override fun ruiCreate() {
        fragment.ruiCreate()
    }

    override fun ruiMount(bridge : RuiBridge<BT>) {
        fragment.ruiMount(bridge)
    }

    override fun ruiPatch() {
        fragment.ruiPatch()
    }

    override fun ruiUnmount(bridge: RuiBridge<BT>) {
        fragment.ruiUnmount(bridge)
    }

    override fun ruiDispose() {
        fragment.ruiDispose()
    }

}