version: '3.8'

services:

  demo-db:
    image: postgres:9.6.21
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - '25432:5432'
    restart: on-failure
    networks:
      - demo-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  demo-srv:
    image: spxbhuhb/zakadabar-demo:2021.3.26
    depends_on:
      demo-db:
        condition: service_healthy
    ports:
      - '8080:8080'
    networks:
      - demo-network

networks:
  demo-network:

