/*
 * Copyright © 2020-2021, Simplexion, Hungary and contributors. Use of this source code is governed by the Apache 2.0 license.
 */
package zakadabar.lib.bender.frontend

import zakadabar.stack.frontend.resources.css.ZkCssStyleSheet
import zakadabar.stack.frontend.resources.css.cssStyleSheet

val benderStyles by cssStyleSheet(BenderStyles())

class BenderStyles : ZkCssStyleSheet() {

    val editor by cssClass {
        margin = "auto"
        maxWidth = "800px"
    }

    val mediumInput by cssClass {
        width = "10em"
    }

    val largeInput by cssClass {
        width = "16em"
    }

    val extraLargeInput by cssClass {
        width = "24em"
    }

    val editorLabel by cssClass {
        fontSize = "80%"
        alignSelf = "center"
        marginRight = 5
    }

    val constraintEditor by cssClass {
        marginRight = 10
        alignSelf = "center"
    }

    val lastGenerated by cssClass {
        marginRight = 10
        alignSelf = "center"
    }
}