/*
 * Copyright © 2020-2021, Simplexion, Hungary and contributors. Use of this source code is governed by the Apache 2.0 license.
 */
package zakadabar.lib.examples.frontend.theme

import zakadabar.core.resource.ZkColors
import zakadabar.core.resource.css.ZkCssStyleSheet
import zakadabar.core.resource.css.px

/**
 * CSS styles are usually defined in objects.
 */
object DemoStyles : ZkCssStyleSheet() {

    // Define a style. The actual name of the CSS class is generated by
    // the stack and is stored in this variable.

    val exampleStyle by cssClass {

        // You can use pre-defined helpers to access most properties

        color = ZkColors.Red.c600
        backgroundColor = ZkColors.Gray.c300

        // If there is no helper, just add directly to [styles]

        styles["font-family"] = "monospace"

        // Some pseudo classes have helpers

        hover {
            color = ZkColors.white
        }

        // For the ones without helper use [on]

        on(":disabled") {
            color = ZkColors.white
        }

        // You can use media queries with [media]

        media("(min-width: 800px)") {
            width = 300.px
        }

        // You can use [on] directly for media queries

        on(media = "(min-width: 1200px)") {
            width = 600.px
        }

        // small = (max-width: 600px)
        // medium = (min-width: 800px)
        // large = (min-width: 1200px)

        small {
            fontSize = 12.px
        }

        medium {
            fontSize = 14.px
        }

        large {
            fontSize = 16.px
        }
    }

    val exampleButtonStyle by cssClass {
        border = "8px solid ${ZkColors.Green.a100}"
    }

}